### PR TITLE
added config files for windows

### PR DESCRIPTION
**Pull request by Harishwarrior**
Added configuration for windows.

### CODE REVIEW

**Comment by Harishwarrior** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nileshtrivedi** [comment]
Thank you so much for the PR @Harishwarrior ! 👏 

I don't have a Windows machine, so I'm unable to test your changes. 

- Does this PR build and generate a Windows app successfully? Please share a screenshot.
- What remains pending for having DevToolBox ready for Windows? I suggest you create separate issues for each of the pending tasks and mention issue ID in your future PRs?

**Comment by Harishwarrior** [comment]
Screenshots: 

image

image

image

image

image

**Comment by Harishwarrior** [comment]
Some error handling needs to be done in code. I'll work on it this week.

**Comment by Harishwarrior** [comment]
Here is a build for windows :
I have tested all the features. Just extract and run the .exe file

[devtoolbox_windows_build.zip](https://github.com/nileshtrivedi/devtoolbox/files/7852832/devtoolbox_windows_build.zip)

**Comment by nileshtrivedi** [comment]
@Harishwarrior Awesome! Let me know when your error handling code is committed. Will merge this PR and announce more broadly.

**Comment by Harishwarrior** [comment]
> @Harishwarrior Awesome! Let me know when your error handling code is committed. Will merge this PR and announce more broadly.

Config files are working so you can merge this PR now. I'll create an issue and PR for error handling seperately.

**Comment by nileshtrivedi** [comment]
@Harishwarrior Published as v0.2.0: https://github.com/nileshtrivedi/devtoolbox/releases/tag/v0.2.0

Thanks a lot! 👏 😄

**Pull request merged**
